-- 코드를 입력하세요
SELECT SUBSTR(A.SALES_DATE, 1, 10), A.PRODUCT_ID, A.USER_ID, A.SALES_AMOUNT
FROM (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE 
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
    UNION
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE 
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
) AS A
ORDER BY A.SALES_DATE, A.PRODUCT_ID, A.USER_ID
;