-- 코드를 입력하세요
# SELECT *
# from FIRST_HALF;

SELECT A.INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
from ICECREAM_INFO A
JOIN FIRST_HALF B ON A.FLAVOR = B.FLAVOR
GROUP BY A.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER
;